name: Websocket
version: 1.0-SNAPSHOT
main: me.senyitko.main.Main
api-version: 1.16
authors: [ Senyitko ]
commands:
  tp:
    description: Teleport to a player
  ping:
    description: Ping a location
  death:
    description: Check Death Location
  help:
    description: Check Help Menu
  name:
    description: Rename an item
